### ISSUE TITLE
Add CF sites to CF protection

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/link-checker#21]
https://github.com/grammyjs/website/actions/runs/9963138706/job/27528495103?pr=1094#step:4:3310

**Comment by dcdunkan** [comment]
Added in https://github.com/grammyjs/link-checker/commit/11c08c4b02576062535ae99d89b8813688837430.

Apparently not all CF sites are covered by CF protection. But they could be, at any moment; so I added glob support and just wildcarded all cloudflare.com subdomains. And of course, I had to make the CLI stop complaining if the site was covered by a wildcard, but not protected, as it previously did. Which, if you think, is kind of ridiculous I believe, because if it's not protected, the other checks are done as normal, and I think (?) we don't need to know whether it's unprotected or not.
